Taxtation/Controllers/SetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Rotativa.AspNetCore;
using Taxtation.App_Code;
using Taxtation.Models;
using Taxtation.Services;
using Taxtation.ViewModel;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;

namespace Taxtation.Controllers
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class SetupController : Controller
    {
        TX tX = new TX();
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        private readonly UrlEncoder _urlEncoder;
        private const string AuthenticatorUriFormat = "otpauth://totp/{0}:{1}?secret={2}&issuer={0}&digits=6";
        private const string RecoveryCodesKey = nameof(RecoveryCodesKey);
        TAXTATIONContext db = new TAXTATIONContext();
        public SetupController(
          UserManager<ApplicationUser> userManager,
          SignInManager<ApplicationUser> signInManager,
          IEmailSender emailSender,
          ILogger<ManageController> logger,
          UrlEncoder urlEncoder)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _logger = logger;
            _urlEncoder = urlEncoder;

        }

        [TempData]
        public string StatusMessage { get; set; }

        #region Currency


        [HttpGet]
        public async Task<IActionResult> showCurrency()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            List<TxscurrencyDetail> lstCurrency = new List<TxscurrencyDetail>();
            lstCurrency = db.TxscurrencyDetail.Where(x => x.Id == user.Id && x.UserName == user.UserName).ToList();
            return View(lstCurrency);
        }

        [HttpGet]
        public async Task<IActionResult> Currency(string id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            if (id == null)
            {
                ViewData["_Save"] = "True";
                ViewData["_Update"] = "False";
                TxscurrencyDetail obj = new TxscurrencyDetail();
                obj.CurActive = (obj.CurActive == null) ? true : false;
                obj.CurIsLocal = (obj.CurIsLocal == null) ? false : false;

                return PartialView(obj);
            }
            else
            {
                ViewData["_Save"] = "False";
                ViewData["_Update"] = "True";
                TxscurrencyDetail obj = new TxscurrencyDetail();
                obj = db.TxscurrencyDetail.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.CurId== Convert.ToInt32(id)).FirstOrDefault();
                if (obj != null) { }
                obj.CurActive = (obj.CurActive == true) ? true : false;
                obj.CurIsLocal = (obj.CurIsLocal == true) ? true : false;
                return PartialView(obj);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Currency(TxscurrencyDetail obj, string Save, string Update, string CurActive, string CurIsLocal)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            if (Save != null)
            {
                obj.Id = user.Id;
                obj.UserName = user.UserName;
                obj.CurActive = (CurActive == "true") ? true : false;
                obj.CurIsLocal = (CurIsLocal == "true") ? true : false;
                obj.EnterBy = user.UserName;
                obj.EnterDate = System.DateTime.Now;
                db.TxscurrencyDetail.Add(obj);
                db.SaveChanges();
            }
            if(Update!=null)
            {
                TxscurrencyDetail obj1 = new TxscurrencyDetail();
                obj1 = db.TxscurrencyDetail.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.CurId == obj.CurId).FirstOrDefault();
                if(obj1!=null)
                {
                    obj1.CurName = obj.CurName;
                    obj1.CurAbbr = obj.CurAbbr;
                    obj1.CurActive = (CurActive == "true") ? true : false;
                    obj1.CurIsLocal = (CurIsLocal == "true") ? true : false;
                    obj1.EditBy = Convert.ToString(user);
                    obj1.EditDate = System.DateTime.Now;
                    db.SaveChanges();
                }

            }
            return RedirectToAction("showCurrency");
        }

      
        #endregion

        #region Store

        public async Task<IActionResult> showStore()
        {
            var user = await _userManager.GetUserAsync(User);
            if(User==null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            List<TxsstoreDetail> lstStore = new List<TxsstoreDetail>();
            lstStore = db.TxsstoreDetail.Where(x => x.Id == user.Id && x.UserName == user.UserName).ToList();
            return View(lstStore);
        }

        [HttpGet]
        public async Task<IActionResult> Store(string id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (User == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            if(id == null)
            {
                ViewData["_Save"] = "True";
                ViewData["_Update"] = "False";
                TxsstoreDetail obj = new TxsstoreDetail();
                obj.StrActive = (obj.StrActive == null) ? true : false;
                return PartialView(obj);
            }
            else
            {
                ViewData["_Save"] = "False";
                ViewData["_Update"] = "True";
                TxsstoreDetail obj = new TxsstoreDetail();
                obj = db.TxsstoreDetail.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.StrId == Convert.ToInt32(id)).FirstOrDefault();
                obj.StrActive = (obj.StrActive == true) ? true : false;
                return PartialView(obj);
            }
        }


        [HttpPost]
        public async Task<IActionResult> Store(TxsstoreDetail obj, string StrActive, string Save, string Update)
        {
            var user = await _userManager.GetUserAsync(User);
            if (User == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            if(Save!=null)
            {
                obj.Id = user.Id;
                obj.UserName = user.UserName;
                obj.StrActive = (obj.StrActive == true) ? true : false;
                obj.EnterBy = user.UserName;
                obj.EnterDate = System.DateTime.Now;
                db.TxsstoreDetail.Add(obj);
                db.SaveChanges();
            }
            if(Update!=null)
            {
                TxsstoreDetail obj1 = new TxsstoreDetail();
                obj1 = db.TxsstoreDetail.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.StrId == obj.StrId).FirstOrDefault();
                if(obj1!=null)
                {
                    obj1.StrName = obj.StrName;
                    obj1.StrAbbr = obj.StrAbbr;
                    obj1.StrDesc = obj.StrDesc;
                    obj1.StrActive = (obj.StrActive == true) ? true : false;
                    obj1.EditBy = user.UserName;
                    obj1.EditDate = System.DateTime.Now;
                    db.SaveChanges();
                }
            }
            return RedirectToAction("showStore");
        }

       
        #endregion

        #region Site

        public async Task<IActionResult> showSite()
        {
            var user = await _userManager.GetUserAsync(User);
            HttpContext.Session.SetString("UName", user.UserName);
            HttpContext.Session.SetString("UId", user.Id);
            if (User == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            List<TxssiteDetail> lstSite = new List<TxssiteDetail>();
            lstSite = db.TxssiteDetail.Where(x => x.Id == user.Id && x.UserName == user.UserName).ToList();
            return View(lstSite);
        }

        [HttpGet]
        public async Task<IActionResult> Site(string id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (User == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            if (id == null)
            {
                ViewData["_Save"] = "True";
                ViewData["_Update"] = "False";
                TxssiteDetail obj = new TxssiteDetail();
                obj.SitActive = (obj.SitActive == null) ? true : false;
                obj.SitDefault = (obj.SitDefault == null) ? true : false;
                return PartialView(obj);
            }

Taxtation/Views/Setup/Bank.cshtml
@model Taxtation.Models.TxsbankDetail
<div style="height:25px;"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Bank Detail</h4>
                        <button type="button" class="close" data-dismiss="modal">
                            ×
                        </button>
                    </div>
                    <div class="modal-body">
                        @using (Html.BeginForm("Bank", "Setup", FormMethod.Post))
    {
                    <div>
                        <input type="text" asp-for="BnkId" class="form-control" hidden="hidden" />
                    </div>
                    <div style="float:right;">
                        @Html.CheckBox("BnkActive", Model.BnkActive.Value)Active
                    </div>
                    <div>
                        Name<span class="mandatory">*</span>:
                        <input type="text" asp-for="BnkName" class="form-control" required="required" />
                      
                    </div>
                    <div>
                        Abbriviation<span class="mandatory">*</span>:
                        <input type="text" asp-for="BnkAbbr" class="form-control" required="required" />
                    </div>
                    <div>
                        Bank Branch<span class="mandatory">*</span>:
                        <input type="text" asp-for="BnkBranch" class="form-control" required="required" />
                    </div>
                    <div>
                        Acc. No<span class="mandatory">*</span>:
                        <input type="text" asp-for="BnkAccNo" class="form-control" required="required" />
                    </div>
                    <div>
                        Phone No<span class="mandatory">*</span>:
                        <input type="text" asp-for="BnkPhNo" class="form-control" required="required" />
                    </div>
                    <div>
                        Fax<span class="mandatory">*</span>:
                        <input type="text" asp-for="BnkFax" class="form-control" required="required" />
                    </div>
                    <div>
                        URL:<span class="mandatory">*</span>:
                        <input type="url" asp-for="BnkUrl" class="form-control" required="required" />
                    </div>
                    <div>
                        Email<span class="mandatory">*</span>:
                        <input type="email" asp-for="BnkEmail" class="form-control" required="required" />
                    </div>
                    <div>
                        Description:
                        <input type="text" asp-for="BnkDesc" class="form-control" />
                    </div>

                    <br />
                    <div>
                        @if (ViewData["_Save"].ToString() == "True")
    {
                    <button type="submit" name="Save" id="Save" value="Save" style="background-image:url(../images/button/Save.png)" class="btnControlDML">Save</button>
}
                        @if (ViewData["_Update"].ToString() == "True")
    {
                    <button type="submit" name="Update" id="Update" value="Update" style="background-image:url(../images/button/Update.png)" class="btnControlDML">Update</button>
}
                        <button type="button" id="btnHideModal" data-dismiss="modal" class="btnControlDML" style="float:right;background-image:url(../images/button/Clear.png)">
                            Hide
                        </button>
                    </div>
}
                    </div>

                        

                </div>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Taxtation/Views/Setup/DonationCategory.cshtml
@model Taxtation.Models.TxsdonationCategoryDetail

<div style="height:25px;"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">
                            Donation Category Detail
                            <button type="button" class="close" data-dismiss="modal">
                                ×
                            </button>
                        </h4>
                    </div>
                    <div class="modal-body">
                        @using (Html.BeginForm("DonationCategory", "Setup", FormMethod.Post))
                        {
                            <div style="padding-bottom: 10px;">
                                @Html.ValidationSummary(true)
                            </div>
                            <div style="padding-bottom: 10px;">
                                @if (ViewData["_Save"].ToString() == "True")
                                {
                                    <button type="submit" name="Save" id="Save" value="Save" AccessKey="S" class="form-control-btn buttonsizesetup">S̲AVE</button>
                                }
                                @if (ViewData["_Update"].ToString() == "True")
                                {
                                    <button type="submit" name="Update" id="Update" value="Update" AccessKey="U" class="form-control-btn buttonsizesetup">U̲PDATE</button>
                                }
                            </div>
                            <div>
                                @Html.TextBoxFor(model => model.DcaId, new { @class = "form-control", @Hidden = "Hidden" })
                            </div>
                            <div style="float:right;">
                                @Html.CheckBox("DcaActive", Model.DcaActive.Value)Active
                            </div>
                            <div>
                                Name<span class="mandatory">*</span>:
                                @Html.TextBoxFor(model => model.DcaName, new { @class = "form-control", @required = true })
                            </div>
                            <div>
                                Abbriviation<span class="mandatory">*</span>:
                                @Html.TextBoxFor(model => model.DcaAbbr, new { @class = "form-control", @required = true })
                            </div>
                            <div>
                                Description:
                                @Html.TextAreaFor(model => model.DcaDesc, new { @class = "form-control textareavertical" })
                            </div>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>
    $("#myModal").on("hidden.bs.modal", function () {
      //  alert("Modal is closed");
        window.location.reload();
    });
</script>

Taxtation/Views/Setup/Donor.cshtml
@model Taxtation.ViewModel.TXSDonorDetailView

<div style="height:25px;"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Donor Detail</h4>
                        <button type="button" class="close" data-dismiss="modal">
                            ×
                        </button>
                    </div>
                    <div class="modal-body">
                        @using (Html.BeginForm("Donor", "Setup", FormMethod.Post))
                        {
                            <div>
                                <input type="text" asp-for="master.DnrId" class="form-control" hidden="hidden" />
                            </div>
                            <div style="float:right">
                                @Html.CheckBox("DnrActive", Model.master.DnrActive.Value)Active
                            </div>
                            <div>
                                Name<span class="mandatory">*</span>:
                                <input type="text" asp-for="master.DnrName" class="form-control" required="required" />

                            </div>
                            <div>
                                Address:
                                <input type="text" asp-for="master.DnrAddress" class="form-control" />
                            </div>
                            <div>
                                Phone No:
                                <input type="text" asp-for="master.DnrPhNo" class="form-control" />
                            </div>
                            <div>
                                Fax:
                                <input type="text" asp-for="master.DnrFaxNo" class="form-control" />
                            </div>

                            <div>
                                Email:
                                <input type="email" asp-for="master.DnrEmail" class="form-control" />
                            </div>
                            <div>
                                NTN:
                                <input type="number" asp-for="master.DnrNtn" class="form-control" />
                            </div>
                            <div>
                                STRN:
                                <input type="number" asp-for="master.DnrStrn" class="form-control" />
                            </div>
                            <div>
                                Country<span class="mandatory">*</span>:
                                <select asp-for="master.DnrCountry" class="form-control" required="required">
                                    <option value="">Select</option>
                                    @foreach (var j in Model.lstCountry)
                                    {
                                        <option value=@j.CouCode>@j.CouName</option>
                                    }
                                </select>
                            </div>
                            <div>
                                City<span class="mandatory">*</span>:
                                <select asp-for="master.DnrCity" class="form-control" required="required">
                                    <option value="">Select</option>
                                    @foreach (var j in Model.lstCity)
                                    {
                                        <option value=@j.CtyCode>@j.CtyName</option>
                                    }
                                </select>
                            </div>
                            <div>
                                Description:
                                <input type="text" asp-for="master.DnrDesc" class="form-control" />
                            </div>
                            <br />
                            <div>
                                @if (ViewData["_Save"].ToString() == "True")
                                {
                                    <button type="submit" name="Save" id="Save" value="Save" style="background-image:url(../images/button/Save.png)" class="btnControlDML">Save</button>
                                }
                                @if (ViewData["_Update"].ToString() == "True")
                                {
                                    <button type="submit" name="Update" id="Update" value="Update" style="background-image:url(../images/button/Update.png)" class="btnControlDML">Update</button>
                                }
                                <button type="button" id="btnHideModal" style="float:right;background-image:url(../images/button/Clear.png)" data-dismiss="modal" class="btnControlDML">
                                    Hide
                                </button>
                            </div>
                        }
                    </div>


                </div>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}
<script>
    $(document).ready(function () {
        $('#master_DnrCountry').change(function () {
            var couCode = document.getElementById("master_DnrCountry").value;
            var city = "<option value='-1'>Select</option>";
            $.ajax({
                type: 'GET',
                url: '/Setup/lstCity',
                data: { id: couCode },
                dataType: 'json',
                contentType: "application/json; charset=utf-8",
                success: function (result) {
                    for (var i = 0; i < result.length; i++) {
                        city += "<option value='" + result[i].ctyCode + "'>" + result[i].ctyName + "</option>";
                    }
                    $('#master_DnrCity option').remove();
                    $('#master_DnrCity').append(city);
                },
                error: function () {


                }
            })
        })
    })
</script>

Taxtation/Views/Setup/Site.cshtml
@model Taxtation.Models.TxssiteDetail

<div style="height:25px;"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">
                            Site Detail
                            <button type="button" class="close" data-dismiss="modal">
                                ×
                            </button>
                        </h4>
                    </div>
                    <div class="modal-body">
                        @using (Html.BeginForm("Site", "Setup", FormMethod.Post))
                        {
                            <div style="padding-bottom: 10px;">
                                @Html.ValidationSummary(true)
                            </div>
                            <div style="padding-bottom: 10px;">
                                @if (ViewData["_Save"].ToString() == "True")
                                {
                                    <button type="submit" name="Save" id="Save" value="Save" AccessKey="S" class="form-control-btn buttonsizesetup" onclick="CheckAvailability()">S̲AVE</button>
                                }
                                @if (ViewData["_Update"].ToString() == "True")
                                {
                                    <button type="submit" name="Update" id="Update" value="Update" AccessKey="U" class="form-control-btn buttonsizesetup" onclick="CheckAvailability()">U̲PDATE</button>
                                }
                            </div>
                            <div>
                                @Html.TextBoxFor(model => model.SitId, new { @class = "form-control", @Hidden = "Hidden" })
                            </div>
                            <div style="float:right;">
                                @Html.CheckBox("SitActive", Model.SitActive.Value)Active
                                &nbsp;
                                @Html.CheckBox("SitDefault", Model.SitDefault.Value)Default
                            </div>
                            <div>
                                Name<span class="mandatory">*</span>:
                                @Html.TextBoxFor(model => model.SitName, new { @class = "form-control", @required = true })
                            </div>
                            <div>
                                Abbriviation<span class="mandatory">*</span>:
                                @Html.TextBoxFor(model => model.SitAbbr, new { @class = "form-control", @required = true })
                            </div>
                            <div>
                                Description:
                                @Html.TextAreaFor(model => model.SitDesc, new { @class = "form-control textareavertical" })
                            </div>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">

   function CheckAvailability() {
            //var Default = $("#SitDefault").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("DefaultCheck","Setup")',
                //data: '{SitDefault: "' + Default + '" }',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    if (response) {
                        //Email available.
                        //event.stopImmediatePropagation();
                        alert("Default Value Already Set");
                    }
                    //else {
                    //    //Email not available.
                    //    alert("Data Saved Successfully");
                    //}
                }
            });
        };
</script>

Taxtation/Views/Setup/Store.cshtml
@model Taxtation.Models.TxsstoreDetail

<div style="height:25px;"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Store Detail</h4>
                        <button type="button" class="close" data-dismiss="modal">
                            ×
                        </button>
                    </div>
                    <div class="modal-body">
                        @using (Html.BeginForm("Store", "Setup", FormMethod.Post))
    {
                    <div>
                        @Html.TextBoxFor(model => model.StrId, new { @class = "form-control", @Hidden = "Hidden" })
                    </div>
                    <div style="float:right"> @Html.CheckBox("StrActive", Model.StrActive.Value)Active</div>
                    <div>
                        Name<span class="mandatory">*</span>:
                        @Html.TextBoxFor(model => model.StrName, new { @class = "form-control", @required = true })
                       
                    </div>
                    <div>
                        Abbriviation<span class="mandatory">*</span>:
                        @Html.TextBoxFor(model => model.StrAbbr, new { @class = "form-control", @required = true })
                    </div>
                    <div>
                        Description:
                        @Html.TextBoxFor(model => model.StrDesc, new { @class = "form-control" })
                    </div>


                    <br />
                    <div>
                        @if (ViewData["_Save"].ToString() == "True")
    {
                    <button type="submit" name="Save" id="Save" value="Save" style="background-image:url(../images/button/Save.png)" class="btnControlDML">Save</button>
}
                        @if (ViewData["_Update"].ToString() == "True")
    {
                    <button type="submit" name="Update" id="Update" value="Update" style="background-image:url(../images/button/Update.png)" class="btnControlDML">Update</button>
}
                        <button type="button" style="float:right;background-image:url(../images/button/Clear.png)" id="btnHideModal" data-dismiss="modal" class="btnControlDML">
                            Hide
                        </button>
                    </div>
}
                    </div>

                  

                </div>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}