Taxtation/Controllers/GeneralLedgerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Rotativa.AspNetCore;
using Taxtation.App_Code;
using Taxtation.Models;
using Taxtation.Models.ManageViewModels;
using Taxtation.Services;
using Taxtation.ViewModel;

namespace Taxtation.Controllers
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class GeneralLedgerController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        private readonly UrlEncoder _urlEncoder;
        private const string AuthenticatorUriFormat = "otpauth://totp/{0}:{1}?secret={2}&issuer={0}&digits=6";
        private const string RecoveryCodesKey = nameof(RecoveryCodesKey);
        TAXTATIONContext db = new TAXTATIONContext();
        TX tX = new TX();
        public GeneralLedgerController(
          UserManager<ApplicationUser> userManager,
          SignInManager<ApplicationUser> signInManager,
          IEmailSender emailSender,
          ILogger<TransactionController> logger,
          UrlEncoder urlEncoder)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _logger = logger;
            _urlEncoder = urlEncoder;
        }

        [TempData]
        public string StatusMessage { get; set; }

        #region Opening Detail
        [HttpGet]
        public async Task<IActionResult> showOpeningDetail()
        {
            var user = await _userManager.GetUserAsync(User);
            if (User == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            HttpContext.Session.SetString("UserId", user.Id);
            HttpContext.Session.SetString("UserName", user.UserName);
            TXTOpeningDetailView obj = new TXTOpeningDetailView();
            obj.lstMaster = db.TxtopeningMaster.Where(x => x.Id == user.Id && x.UserName == user.UserName).ToList();
            obj.lstLedger = db.Txtledger.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.Trtype == "OPENING" && x.TrentryType == "CHILD").ToList();
            obj.lstSite = db.TxssiteDetail.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.SitActive == true).ToList();
            //obj.lstSite.Select(x => x.Id == user.Id && x.UserName == user.UserName && x.SitActive == true).ToList();

            obj.lstCurrency = db.TxscurrencyDetail.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.CurActive == true).ToList();
            obj.lstAccount = db.Txscoadetail.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.AccActive == true).ToList();
            return View(obj);
        }

        [HttpGet]
        public async Task<IActionResult> OpeningDetail(string id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (User == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            HttpContext.Session.SetString("UserId", user.Id);
            HttpContext.Session.SetString("UserName", user.UserName);
            TXTOpeningDetailView obj = new TXTOpeningDetailView();
            obj.lstSite = db.TxssiteDetail.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.SitActive == true).ToList();
            obj.lstCurrency = db.TxscurrencyDetail.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.CurActive == true).ToList();
            obj.lstAccount = db.Txscoadetail.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.AccAccountType == "TRANSACTION" && x.AccActive == true).ToList();

            if (id == null)
            {
                ViewData["_Save"] = "True";
                ViewData["_Update"] = "False";
                obj.master.Trno = tX.OpeningDetail(user.Id, user.UserName);
                obj.master.Trdate = DateTime.Now;
                obj.master.Trgldate = DateTime.Now;
                obj.master.TrexchangeRate = 1;
                obj.lstLedger = null;
                obj.eFOD = null;
            }
            else
            {
                ViewData["_Save"] = "False";
                ViewData["_Update"] = "True";
                obj.master = db.TxtopeningMaster.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.TrId == Convert.ToInt32(id)).FirstOrDefault();
                obj.lstLedger = db.Txtledger.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.Trno == obj.master.Trno && x.TrentryType == "CHILD").OrderBy(x => x.TrserialNo).ToList();
                for (int i = 0; i < obj.lstLedger.Count; i++)
                {
                    EFOD eFOD = new EFOD();
                    if (obj.lstLedger[i].Trdebit != 0) { eFOD.amount = obj.lstLedger[i].Trdebit; eFOD.debitCredit = "001"; }
                    if (obj.lstLedger[i].Trcredit != 0) { eFOD.amount = obj.lstLedger[i].Trcredit; eFOD.debitCredit = "002"; }
                    obj.eFOD.Add(eFOD);
                }
                obj.TotalCredit = obj.lstLedger.Sum(x => x.Trcredit);
                obj.TotalDebit = obj.lstLedger.Sum(x => x.Trdebit);
            }
            return View(obj);
        }
        [HttpPost]
        public async Task<IActionResult> OpeningDetail(TXTOpeningDetailView obj, string Save, string Update, string Delete, string TraAdusting)
        {
            var user = await _userManager.GetUserAsync(User);
            if (User == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            HttpContext.Session.SetString("UserId", user.Id);
            HttpContext.Session.SetString("UserName", user.UserName);
            if (Save != null)
            {
                obj.master.Id = user.Id;
                obj.master.UserName = user.UserName;
                obj.master.Trno = tX.OpeningDetail(user.Id, user.UserName);
                obj.master.EnterBy = user.UserName;
                obj.master.EnterDate = DateTime.Now;
                obj.master.TrtotalAmount = obj.TotalCredit;
                db.TxtopeningMaster.Add(obj.master);
                db.SaveChanges();
                int k = 0;
                for (int i = 0; i < obj.lstLedger.Count; i++)
                {
                    if (obj.lstLedger[i].TraccCode != "-1" && obj.eFOD[i].amount != null)
                    {
                        if (obj.eFOD[i].debitCredit == "001") { obj.lstLedger[i].Trcredit = 0; obj.lstLedger[i].Trdebit = obj.eFOD[i].amount; }
                        if (obj.eFOD[i].debitCredit == "002") { obj.lstLedger[i].Trcredit = obj.eFOD[i].amount; obj.lstLedger[i].Trdebit = 0; }
                        k = k + 1;
                        tX.insertLedgerDetail(user.Id, user.UserName, obj.master.Trno, obj.master.Trdate, obj.master.Trgldate, "OPENING", "UN-POST", k, obj.lstLedger[i].TraccCode, obj.lstLedger[i].TraccCode, "", obj.lstLedger[i].Trdebit, obj.lstLedger[i].Trcredit, obj.master.TrexchangeRate, obj.lstLedger[i].TramountConverted, obj.master.TrcurId, 0, 0, 0, "", null, obj.lstLedger[i].TrrefNo, obj.lstLedger[i].Trremarks, "CHILD", user.UserName, DateTime.Now, "Opening Detail", obj.master.SitId, "CHILD", 0, 0, 0);
                        //k = k + 1;
                        //tX.insertLedgerDetail(user.Id, user.UserName, obj.master.Trno, obj.master.Trdate, obj.master.Trgldate, "OPENING", "UN-POST", k, obj.lstLedger[i].TraccCode, obj.lstLedger[i].TraccCode, "", obj.lstLedger[i].Trdebit, obj.lstLedger[i].Trcredit, obj.master.TrexchangeRate, obj.lstLedger[i].TramountConverted, obj.master.TrcurId, 0, 0, 0, "", null, obj.lstLedger[i].TrrefNo, obj.lstLedger[i].Trremarks, "TOTAL", user.UserName, DateTime.Now, "Opening Detail", obj.master.SitId, "PARENT", 0, 0, 0);
                    }
                }
            }
            if (Update != null)
            {
                TxtopeningMaster objUpdate = new TxtopeningMaster();
                objUpdate = db.TxtopeningMaster.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.TrId == obj.master.TrId).FirstOrDefault();
                if (objUpdate != null)
                {
                    objUpdate.Trdate = obj.master.Trdate;
                    objUpdate.Trgldate = obj.master.Trgldate;
                    objUpdate.SitId = obj.master.SitId;
                    objUpdate.TrtotalAmount = obj.TotalCredit;
                    objUpdate.TrmainRemarks = obj.master.TrmainRemarks;
                    objUpdate.TrexchangeRate = obj.master.TrexchangeRate;
                    objUpdate.TrcurId = obj.master.TrcurId;
                    objUpdate.TrrefMain = obj.master.TrrefMain;
                    objUpdate.EditBy = user.UserName;
                    objUpdate.EditDate = DateTime.Now;
                    db.SaveChanges();
                }


                //obj.lstLedger = db.Txtledger.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.Trno == obj.master.Trno).ToList();
                //for (int i = 0; i < obj.lstLedger.Count; i++)
                //{
                //    db.Txtledger.Remove(obj.lstLedger[i]);
                //    db.SaveChanges();
                //}

                db.Txtledger.RemoveRange(db.Txtledger.Where(x => x.Id == user.Id && x.UserName == user.UserName && x.Trno == obj.master.Trno));
                db.SaveChanges();

Taxtation/Views/GeneralLedger/FundTransferDetail.cshtml
@model Taxtation.ViewModel.TXTFundTransferDetailView

@{
    ViewData["Title"] = "Fund Transfer Detail";
    var index = 5;
    if (Model.lstLedger != null)
    {
        index = Model.lstLedger.Count;
    }
}
<form asp-action="FundTransferDetail" method="post">
    <div class="row" style="position:fixed;padding-top:10px;z-index:2;background-color:#EEEEEE;left:0;right:0">
        <div class="col-sm-12" style="padding-left:8.2%;">
            @if (ViewData["_Save"].ToString() == "True")
            {
                <button type="submit" name="Save" id="Save" value="Save" style="background-image:url(../images/button/Save.png)" class="btnControlDML">Save</button>
            }
            @if (ViewData["_Update"].ToString() == "True")
            {
                <button type="submit" name="Update" id="Update" value="Update" style="background-image:url(../images/button/Update.png)" class="btnControlDML">Update</button>
                <button type="submit" name="Delete" id="Delete" value="Delete" style="background-image:url(../images/button/Delete.png)" class="btnControlDML">Delete</button>
                <button type="submit" name="Report" id="Report" value="Report" style="background-image:url(../images/button/Report.png)" class="btnControlDML">Report</button>
            }
            <div style="float:right;padding-right:8.3%">
                <a asp-action="showFundTransferDetail" asp-controller="GeneralLedger" style="background-image:url(../images/button/back.png)" class="btnControlDML">Back</a>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-lg-4">
            <input type="text" asp-for="master.TrId" hidden="hidden" class="form-control" />
        </div>
    </div>
    <div class="row" style="padding-top:70px;z-index:1">
        <div class="col-md-3">
            Transaction No<span class="mandatory">*</span>:
            <input type="text" asp-for="master.Trno" readonly="readonly" class="form-control" />
        </div>
        <div class="col-md-3">
            Transaction Date<span class="mandatory">*</span>:
            <input type="date" asp-for="master.Trdate" class="form-control" required />
        </div>
        <div class="col-md-3">
            GL Date<span class="mandatory">*</span>:
            <input type="date" asp-for="master.Trgldate" class="form-control" required />

        </div><div class="col-md-3">
            Site<span class="mandatory">*</span>:
            <select asp-for="master.SitId" class="form-control" required="required">
                <option value="">Select</option>
                @foreach (var j in Model.lstSite)
                {
                    <option value=@j.SitId>@j.SitName</option>
                }
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            Currency<span class="mandatory">*</span>:
            <select asp-for="master.TrcurId" class="form-control" required="required">
                <option value="">Select</option>
                @foreach (var j in Model.lstCurrency)
                {
                    <option value=@j.CurId>@j.CurName</option>
                }
            </select>
        </div>
        <div class="col-md-3">
            Exchange Rate<span class="mandatory">*</span>:
            <input type="number" asp-for="master.TrexchangeRate" onchange="ExchangeRate()" class="form-control" required="required" />
        </div>
        <div class="col-md-3">
            Reference No:
            <input type="text" asp-for="master.TrrefMain" class="form-control" />
        </div>
        <div class="col-md-3">

        </div>
    </div>

    <div class="row">

        <div class="col-md-12">
            Remarks:
            <input type="text" asp-for="master.TrmainRemarks" class="form-control" />
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-3">
            <button id="addNewRow" class="form-control">Add New Row</button>
        </div>
        <div class="col-lg-9"></div>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-12" style="overflow-x:scroll;">
            <table id="myTable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th style="width:230px;">Account From</th>
                        <th style="width:230px;">Account To</th>
                        <th style="width:120px;">Amount</th>
                        <th style="width:120px;">Exc. Amount</th>
                        <th style="width:120px;">Cheque No</th>
                        <th style="width:120px;">Cheque Date</th>
                        <th style="width:350px;">Remarks</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < index; i++)
                    {
                        <tr>
                            <td>
                                <select asp-for="lstLedger[i].TraccCode" onchange="ExchangeRate()" class="form-control" style="width:230px;">
                                    <option value="-1">Select</option>@foreach (var j in Model.lstAccount)
                                    {
                                        <option value=@j.AccCode>@j.AccName</option>}
                                </select>
                            </td>
                            <td>
                                <select asp-for="lstLedger[i].TrrefAccCode" onchange="ExchangeRate()" class="form-control" style="width:230px;">
                                    <option value="-1">Select</option>@foreach (var j in Model.lstAccount)
                                    {
                                        <option value=@j.AccCode>@j.AccName</option>}
                                </select>
                            </td>
                            <td><input type="text" asp-for="lstLedger[i].Trdebit" onchange="ExchangeRate()" class="form-control" style="width:120px;" /></td>
                            <td><input type="number" step="any" asp-for="lstLedger[i].TramountConverted" class="form-control" style="width:120px;" /></td>
                            <td><input type="text" asp-for="lstLedger[i].TrchequeNo" class="form-control" style="width:120px;" /></td>
                            <td><input type="date" asp-for="lstLedger[i].TrchequeDate" class="form-control" style="width:170px;" /></td>
                            <td><input type="text" asp-for="lstLedger[i].Trremarks" class="form-control" style="width:350px;" /></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <br />

</form>


@section Scripts{
    <script type="text/javascript">

        $(window).load(function () {
            ExchangeRate();
        });

        function ExchangeRate() {

            var ExRate = $('#master_TrexchangeRate').val();
            var rows = $('#myTable tbody tr').length;
            for (var i = 0; i < rows; i++) {

                if ($('#lstLedger_' + i + '__TraccCode').val() != '-1' && $('#lstLedger_' + i + '__TrrefaccCode').val() != '-1' && $('#eFFT_' + i + '__amount').val() != '') {
                    if (ExRate != '') {

                        $('#lstLedger_' + i + '__TramountConverted').val(parseFloat($('#eFFT_' + i + '__amount').val() * ExRate).toFixed(2));
                    }
                    else { $('#lstLedger_' + i + '__TramountConverted').val(0); }
                }

            }


        }

        $('#addNewRow').click(function (event) {
            var rowCount = $('#myTable tbody tr').length;
            var dropDownAccountTo = document.getElementById('lstLedger_0__TraccCode').innerHTML;
            var dropDownAccountFrom = document.getElementById('lstLedger_0__TrrefaccCode').innerHTML;
            $('#myTable').append('<tr><td><select onchange="ExchangeRate()" class="form-control" style="width:230px;" id="lstLedger_' + rowCount + '__TraccCode" name="lstLedger[' + rowCount + '].TraccCode">< option value = "-1" > Select</option >' + dropDownAccountTo + '</select ></td><td><input type="text" onchange="ExchangeRate()" class="form-control" style="width:120px;" data-val="true" data-val-number="The field amount must be a number." id="eFFT_' + rowCount + '__amount" name="eFFT[' + rowCount + '].amount" value=""></td><td><select onchange="ExchangeRate()"  class="form-control" style="width:120px;" id="eFFT_' + rowCount + '__debitCredit" name="eFFT[' + rowCount + '].debitCredit">< option value = "001" > Debit</option ><option value="002">Credit</option></select ></td><td><input type="number" step="any" class="form-control" style="width:120px;" data-val="true" data-val-number="The field TramountConverted must be a number." id="lstLedger_' + rowCount + '__TramountConverted" name="lstLedger[' + rowCount + '].TramountConverted" value=""></td><td><input type="text" class="form-control" style="width:120px;" id="lstLedger_' + rowCount + '__TrrefNo" name="lstLedger[' + rowCount + '].TrrefNo" value=""></td><td><input type="text" class="form-control" style="width:350px;" id="lstLedger_' + rowCount + '__Trremarks" name="lstLedger[' + rowCount + '].Trremarks" value=""></td></tr>')
            $('#lstLedger_' + rowCount + '__TraccCode').attr('Selected', true).val("-1");
            event.preventDefault();
        })

        $(document).ready(function () {
            $('#Save').on('click', function (event) {
                var count = 0;
                var rowCount = $('#myTable tbody tr').length;
                var ExRate = $('#master_TrexchangeRate').val();

                if (ExRate == '' || ExRate == 0) {
                    alert('Please Enter Valid Exchange Rate!');
                    event.preventDefault();
                }
                for (var i = 0; i < rowCount; i++) {
                    if ($('#lstLedger_' + i + '__TraccCode').val() != '-1' && $('#lstLedger_' + i + '__TrrefaccCode').val() != '-1' && $('#eFFT_' + i + '__amount').val() != '') {
                        count++;
                    }
                }
                if (parseFloat(count) == 0) {
                    alert('Please Select Account or Enter Amount!');
                    event.preventDefault();
                }
            })
        })

        $(document).ready(function () {
            $('#Update').on('click', function (event) {
                var count = 0;
                var rowCount = $('#myTable tbody tr').length;
                var ExRate = $('#master_TrexchangeRate').val();

                if (ExRate == '' || ExRate == 0) {
                    alert('Please Enter Valid Exchange Rate!');
                    event.preventDefault();
                }
                for (var i = 0; i < rowCount; i++) {
                    if ($('#lstLedger_' + i + '__TraccCode').val() != '-1' && $('#lstLedger_' + i + '__TrrefaccCode').val() != '-1' && $('#eFFT_' + i + '__amount').val() != '') {
                        count++;
                    }
                }
                if (parseFloat(count) == 0) {
                    alert('Please Select Account or Enter Amount!');
                    event.preventDefault();
                }
            })
        })
    </script>

}

Taxtation/Views/GeneralLedger/ShowOpeningDetail.cshtml
@model Taxtation.ViewModel.TXTOpeningDetailView

@{
    ViewData["Title"] = "List Opening Detail";
    var query = from mas in Model.lstMaster
                join det in Model.lstLedger on mas.Trno equals det.Trno
                join site in Model.lstSite on mas.SitId equals site.SitId into sites
                from site in sites.DefaultIfEmpty()
                join currency in Model.lstCurrency on mas.TrcurId equals currency.CurId into currencies
                from currency in currencies.DefaultIfEmpty()
                join account in Model.lstAccount on det.TraccCode equals account.AccCode into accounts
                from account in accounts.DefaultIfEmpty()
                select new { mas, det, site, currency, account };
}

<div class="MainDiv">
    <div>
        <h2>List Opening Detail</h2>
    </div>
    <div style="float:left;">
        <a asp-action="OpeningDetail" asp-controller="GeneralLedger" AccessKey="A" class="form-control-btn" style="width:100px;">A̲DD NEW</a>
    </div>
    <div style="text-align:right;width:100px;float:left;padding-left:2px;padding-right:1px;">@Html.ActionLink("R̲EPORT", "PrintAllOpening", "Reports", new { }, new { target = "_blank", @class = "form-control-btn", @accesskey = "R" })</div>
    <div style="float:left;">
        <a asp-action="Ledger" asp-controller="Home" AccessKey="B" class="form-control-btn" style="width:100px;">B̲ACK</a>
    </div>
    <div style="float:right;">
        <input type="text" id="myInput" class="form-control" onkeyup="myFunction()" placeholder="Search..." title="Search..." style="width:330px;">
    </div>
</div>
<div class="GridStyle">
    <table class="table table-striped" id="myTable">
        <thead>
            <tr style="white-space:nowrap;">
                <th></th>
                <th>TR. NO.</th>
                <th>TR. DATE</th>
                @*<th>Ledger Date</th>*@
                <th>ACCOUNT NAME</th>
                <th>DEBIT</th>
                <th>CREDIT</th>
                <th>SITE</th>
                <th>CURRENCY</th>
                <th>EXC. RATE</th>
                <th>REF. NO.</th>
                <th>REMARKS</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var j in query)
            {
                <tr style="white-space:nowrap;">
                    @*<td>
                        <a id="btnEdit" class="btnEdits form-control-btn-edit" data-url='@Url.Action("OpeningDetail","GeneralLedger", new { id=j.mas.TrId })'>Edit</a>
                    </td>*@
                    <td>@Html.ActionLink("Edit", "OpeningDetail", "GeneralLedger", new { id = j.mas.TrId}, new { @class = "form-control-btn-edit" })</td>
                    <td>@Html.DisplayFor(modelItem => j.mas.Trno)</td>
                    <td>@Convert.ToString(string.Format("{0:dd-MMM-yyyy}", j.mas.Trdate))</td>
                    @*<td>@Html.DisplayFor(modelItem => j.mas.Trgldate)</td>*@
                    <td>@Html.DisplayFor(modelItem => j.account.AccName)</td>
                    <td>@String.Format("{0:n0}", j.det.Trdebit)</td>
                    <td>@String.Format("{0:n0}", j.det.Trcredit)</td>
                    <td>@Html.DisplayFor(modelItem => j.site.SitName)</td>
                    <td>@Html.DisplayFor(modelItem => j.currency.CurName)</td>
                    <td>@Html.DisplayFor(modelItem => j.mas.TrexchangeRate)</td>
                    <td>@Html.DisplayFor(modelItem => j.mas.TrrefMain)</td>
                    <td>@Html.DisplayFor(modelItem => j.mas.TrmainRemarks)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts{   
    <script type="text/javascript">
        function myFunction() {
            debugger;
            var input, filter, table, tr, td, i, txtValue, j;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            var tds = $('#myTable').children('tbody').children('tr').children('td').length;
            tds = tds / tr.length;
            for (i = 1; i < tr.length; i++) {
                for (j = 0; j < tds; j++) {
                    td = tr[i].getElementsByTagName("td")[j];
                    if (td) {
                        txtValue = td.textContent || td.innerText;
                        if (txtValue.toUpperCase().indexOf(filter) > -1) {
                            tr[i].style.display = "";
                            break;
                        } else {
                            tr[i].style.display = "none";
                        }
                    }
                }
            }
        }
    </script>
}

Taxtation/Views/GeneralLedger/showFundTransferDetail.cshtml
@model Taxtation.ViewModel.TXTFundTransferDetailView

@{
    ViewData["Title"] = "show Fund Transfer Detail";
    var query = from mas in Model.lstMaster
                join det in Model.lstLedger on mas.Trno equals det.Trno
                join site in Model.lstSite on mas.SitId equals site.SitId into sites
                from site in sites.DefaultIfEmpty()
                join currency in Model.lstCurrency on mas.TrcurId equals currency.CurId into currencies
                from currency in currencies.DefaultIfEmpty()
                join account in Model.lstAccount on det.TraccCode equals account.AccCode into accounts
                from account in accounts.DefaultIfEmpty()
                select new { mas, det, site, currency, account };
}


<div class="MainDiv">
    <div>
        <h2>List Fund Transfer Detail</h2>
    </div>
    <br />
    <div style="float:left;">
        <a asp-action="FundTransferDetail" asp-controller="GeneralLedger" class="form-control-btn" style="width:120px;">Add New</a>
    </div>
    <div style="text-align:right;width:120px;float:left;padding-left:2px;">@Html.ActionLink("Report", "PrintAllPurchase", "Reports", new { }, new { target = "_blank", @class = "form-control-btn" })</div>
    <div style="float:right;">
        <input type="text" id="myInput" class="form-control" onkeyup="myFunction()" placeholder="Search..." title="Type in a name">
    </div>
</div>
<div class="GridStyle">
    <table class="table table-striped" id="myTable">
        <thead>
            <tr>
                <th></th>
                <th>Transaction No</th>
                <th>Transaction Date</th>
                <th>Ledger Date</th>
                <th>Site</th>
                <th>Currency</th>
                <th>Exchange Rate</th>
                <th>Reference No</th>
                <th>Remarks</th>
                <th>Account</th>
                <th>Credit</th>
                <th>Debit</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var j in query)
            {
                <tr>
                    <td>@Html.ActionLink("Edit", "FundTransferDetail", "GeneralLedger", new { id = j.mas.TrId })</td>
                    <td>@Html.DisplayFor(modelItem => j.mas.Trno)</td>
                    <td>@Html.DisplayFor(modelItem => j.mas.Trdate)</td>
                    <td>@Html.DisplayFor(modelItem => j.mas.Trgldate)</td>
                    <td>@Html.DisplayFor(modelItem => j.site.SitName)</td>
                    <td>@Html.DisplayFor(modelItem => j.currency.CurName)</td>
                    <td>@Html.DisplayFor(modelItem => j.mas.TrexchangeRate)</td>
                    <td>@Html.DisplayFor(modelItem => j.mas.TrrefMain)</td>
                    <td>@Html.DisplayFor(modelItem => j.mas.TrmainRemarks)</td>
                    <td>@Html.DisplayFor(modelItem => j.account.AccCode)</td>
                    <td>@Html.DisplayFor(modelItem => j.det.Trcredit)</td>
                    <td>@Html.DisplayFor(modelItem => j.det.Trdebit)</td>

                </tr>

            }
        </tbody>
    </table>
</div>

@section Scripts{
    <script type="text/javascript">

        function myFunction() {
            debugger;
            var input, filter, table, tr, td, i, txtValue, j;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            var tds = $('#myTable').children('tbody').children('tr').children('td').length;
            tds = tds / tr.length;
            for (i = 1; i < tr.length; i++) {
                for (j = 0; j < tds; j++) {
                    td = tr[i].getElementsByTagName("td")[j];
                    if (td) {
                        txtValue = td.textContent || td.innerText;
                        if (txtValue.toUpperCase().indexOf(filter) > -1) {
                            tr[i].style.display = "";
                            break;
                        } else {
                            tr[i].style.display = "none";
                        }
                    }
                }
            }
        }
    </script>

}